dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('',include('davur.urls', namespace='davur')),
    # path('frontend/',include('frontend.urls', namespace='frontend')),

    path('davur/',include('davur.urls', namespace='davur')),
    path('',include('frontend.urls', namespace='frontend')),

    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),
    
]
if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header  =  "Davur Dashboard"  
admin.site.site_title  =  "Dashboard"
admin.site.index_title  =  "Dashboard"

davur/urls.py
from django.urls import path
from davur import davur_views
from users import users_views

app_name = 'davur'
urlpatterns = [

    path('users/', users_views.users, name="users"),
    path('user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('add-user/', users_views.add_user, name="add-user"),
    path('edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),

    path('login/', users_views.login_user, name="login"),
    path('logout/', users_views.logout_user, name="logout"),

    path('group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('group-add/', users_views.group_add, name="group-add"),

    path('edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('signup/', users_views.signup, name="signup"),
    path('activate/<uidb64>/<token>/', users_views.activate, name='activate'),

    path('', davur_views.index, name="index"),
    path('dashboard/', davur_views.dashboard, name="dashboard"),
    path('page-analytics/', davur_views.page_analytics, name="page-analytics"),
    path('page-review/', davur_views.page_review, name="page-review"),
    path('page-review/<int:id>', davur_views.filter_review, name="filter-review"),
    path('page-general-customers/', davur_views.page_general_customers, name="page-general-customers"),
    path('page-general-customers/<str:a>', davur_views.filter_customers, name="filter-customers"),
    path('customer-detail/<int:id>', davur_views.customer_detail, name="customer-detail"),
    path('delete-customer/<int:id>', davur_views.delete_customer, name="delete-customer"),
    
    path('online-customers/', davur_views.online_customers, name="online-customers"),


    path('ecom-product-list/', davur_views.ecom_product_list, name="ecom-product-list"),
    path('product-detail/<int:id>', davur_views.product_detail, name="product-detail"),
    path('delete-product/<int:id>', davur_views.delete_product, name="delete-product"),

    # create filter by categories
    path('category/<str:slug>', davur_views.filter_by_categories, name="filter-by-categories"),

    path('ecom-product-order/', davur_views.ecom_product_order, name="ecom-product-order"),

    path('order-status/', davur_views.order_status, name="order-status"),
    path('update-status/<int:id>/<str:status>', davur_views.update_status, name="update-status"),
    
    path('detail-order/<int:id>', davur_views.detail_order, name="detail-order"),

    path('delete-order/<int:id>', davur_views.delete_order, name="delete-order"),

    
    
    

    # demo
    path('demo/', davur_views.revenue, name="revenue"),


]

frontend/urls.py
from django.urls import path
from frontend import frontend_views

app_name = 'frontend'
urlpatterns = [

    # For customer
    path('', frontend_views.home_page, name="home-page"),
    path('sign-up/', frontend_views.register_page, name="register"),
    path('login/', frontend_views.login_page, name="login-page"),
    path('logout/', frontend_views.logout_page, name="logout-page"),

    path('product/<int:id>', frontend_views.product_detail, name="view-product"),
    path('cart/', frontend_views.cart_page, name="cart-page"),
    path('addtocart-onl/', frontend_views.addtocart_online, name="addtocart-online"),
    path('updatecart-onl/', frontend_views.updateCart_online, name ='updatecart-online'),
    path('delete-cart-item-onl/', frontend_views.deleteCartItem_online, name ='delete-cart-item-online'),
    path('delete-null-item-onl/', frontend_views.deleteNullItem_online, name ='delete-null-item-online'),
    path('discount-code/', frontend_views.discount_code, name ='discount-code'),
    
    path('checkout/', frontend_views.checkout_page, name="checkout-page"),
    path('purchase/', frontend_views.purchase_page, name="purchase-page"),
    path('thank-you/<str:id>', frontend_views.thankyou_page, name="thank-you"),

    path('customer_review/<int:id>', frontend_views.customer_review, name ='customer-review'),

    path('order-history/', frontend_views.order_history, name ='order-history'),
    path('tracking-order/', frontend_views.tracking_order, name ='tracking-order'),



    #For store owner

    path('front-authentication/', frontend_views.front_authentication, name="front-authentication"),
    # path('front-people/', frontend_views.front_people, name="front-people"),
    path('front-upload-item/', frontend_views.front_upload_item, name="front-upload-item"),
    # path('front-login/', frontend_views.front_login, name="front-login"),
    path('page-register/', frontend_views.page_register, name="page-register"),
    # path('update_item/', frontend_views.updateItem, name='update-item'),
    path('search/', frontend_views.search, name="search"),
    path('category/<str:slug>/<int:id>', frontend_views.category, name="category"),
    path('table/', frontend_views.table, name = 'table'),
    path('cart/<int:id>', frontend_views.cart, name = 'cart'),
    path('cart-demo/<int:id>', frontend_views.cart_demo, name = 'cart-demo'),
    path('checkout/<int:id>', frontend_views.checkout, name = 'checkout'),
    path('purchase/<pk>', frontend_views.purchase, name = 'purchase'),
    path('success/<int:id>', frontend_views.success, name = 'success'),
    path('addtocart/',frontend_views.addtocart, name='addtocart'),
    path('updatecart/', frontend_views.updateCart, name ='updatecart'),
    path('delete-cart-item/', frontend_views.deleteCartItem, name ='delete-cart-item'),
    path('delete-null-item/', frontend_views.deleteNullItem, name ='delete-null-item'),
    path('chartjs/', frontend_views.chartJs, name ='chart'),
    path('review/<int:id>', frontend_views.review, name ='review'),
    path('thankyou/', frontend_views.thankyou, name ='thankyou'),

    
    

]

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, first_name, last_name, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        super_user = self.create_user(email, first_name, last_name, password, **other_fields)

        return super_user

    def create_user(self, email, first_name, last_name, password, **other_fields):
        # new add
        other_fields.setdefault('is_active', True)
        # email validation
        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **other_fields)
        user.set_password(password)
        user.save()
        return user


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f'{instance.email}/{filename}'


# This is the new custom user model
class CustomUser(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = (
        ('', 'Choose gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    )
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER_CHOICES, blank=True)
    avatar = models.ImageField(upload_to=user_directory_path, default="profile/image/default.gif")
    dob = models.CharField(max_length=150, blank=True, null=True, help_text="Pattern = dd-mm-yyyy")
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # Validators should be a list
    groups = models.ManyToManyField(Group, blank=True)
    about = models.TextField(_('about'), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)  # this false work on ui not in admin
    # when user is created, than system send a email after varify  user is active

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

templates/davur/elements/alert.html
{% if messages %}
<ul class="messages">
{% for message in messages %}
<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>

    <div class="alert alert-{{ message.tags }} alert  alert-dismissible alert-alt solid fade show">
        {% comment %} {% if message.tags == 'danger' %}
        <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="me-2"><polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon><line x1="15" y1="9" x2="9" y2="15"></line><line x1="9" y1="9" x2="15" y2="15"></line></svg>
         {% elif message.tags == 'success' %}
         <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="me-2"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg>
         {% elif message.tags == 'warning' %}
         <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="me-2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>

        {% endif %} {% endcomment %}

        <div class="media">
            <div class="media-body">
                <p class="mb-0"> {{ message}}</p>
            </div>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close">
        </button>
    </div>

</li>
{% endfor %}
</ul>
{% endif %}

templates/davur/elements/footer.html
{% load static %}

<div class="footer">
    <div class="copyright">
        <p>Copyright © Designed &amp; Developed by <a href="http://dexignzone.com/" target="_blank">DexignZone</a> 2022</p>
    </div>
</div>

templates/davur/elements/nav-header.html
{% load static %}

<div class="nav-header">
    <a href="{% url 'davur:index' %}" class="brand-logo">
        <img class="logo-abbr" src="{% static 'davur/images/logo.png' %}" alt="">
        <img class="logo-compact" src="{% static 'davur/images/logo-text.png' %}" alt="">
        <img class="brand-title" src="{% static 'davur/images/logo-text.png' %}" alt="">
    </a>

    <div class="nav-control">
        <div class="hamburger">
            <span class="line"></span><span class="line"></span><span class="line"></span>
        </div>
    </div>
</div>

templates/davur/elements/sidebar.html
{% load static %}
<div class="deznav">
    <div class="deznav-scroll">
        <ul class="metismenu" id="menu">

            {% if perms.users.view_customuser or perms.auth.view_group or perms.auth.view_permission %}
                {% if perms.users.view_customuser or perms.users.change_customuser or perms.users.add_customuser or perms.users.delete_customuser %}
                    <li>
                        <a href="{% url 'davur:users' %}">
                            <i class="flaticon-381-user ai-icon" aria-expanded="false"></i>
                            <span class="nav-text">Users</span>
                        </a>
                    </li>
                

                    <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                            <i class="flaticon-381-home"></i>
                            <span class="nav-text">Dashboard</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'davur:dashboard' %}">Dashboard</a></li>
                            <li><a href="{% url 'davur:page-analytics' %}">Analytics</a></li>
                            <li><a href="{% url 'davur:page-review' %}">Review</a></li>
                            <li><a href="{% url 'davur:page-general-customers' %}">Customers</a></li>
                            
                        </ul>
                    </li>

                    <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                            <i class="flaticon-381-list"></i>
                            <span class="nav-text">Shop</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'davur:ecom-product-list' %}">Product List</a></li>
                            <li><a href="{% url 'davur:ecom-product-order' %}">Order List</a></li>
                            <li><a href="{% url 'frontend:front-upload-item' %}">Upload Product</a></li>
                        </ul>
                    </li>
                {% endif %}
            {% endif %}



            <li><a class="has-arrow ai-icon" href="javascript:void()" aria-expanded="false">
                    <i class="flaticon-381-user-9"></i>
                    <span class="nav-text">Order Food</span>
                   
                </a>
                <ul aria-expanded="false">
                    <li><a href="{% url 'frontend:table' %}">Choose Table</a></li>
                    <li><a href="{% url 'davur:order-status' %}">Online Order Status</a></li>
                    
                </ul>
            </li>
        </ul>
    </div>
</div>