dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('',include('davur.urls', namespace='davur')),
    # path('frontend/',include('frontend.urls', namespace='frontend')),

    path('davur/',include('davur.urls', namespace='davur')),
    path('',include('frontend.urls', namespace='frontend')),

    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),
    
]
if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header  =  "Davur Dashboard"  
admin.site.site_title  =  "Dashboard"
admin.site.index_title  =  "Dashboard"

davur/urls.py
from django.urls import path
from davur import davur_views
from users import users_views

app_name = 'davur'
urlpatterns = [

    path('users/', users_views.users, name="users"),
    path('user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('add-user/', users_views.add_user, name="add-user"),
    path('edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),

    path('login/', users_views.login_user, name="login"),
    path('logout/', users_views.logout_user, name="logout"),

    path('group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('group-add/', users_views.group_add, name="group-add"),

    path('edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('signup/', users_views.signup, name="signup"),
    path('activate/<uidb64>/<token>/', users_views.activate, name='activate'),

    path('', davur_views.index, name="index"),
    path('dashboard/', davur_views.dashboard, name="dashboard"),
    path('page-analytics/', davur_views.page_analytics, name="page-analytics"),
    path('page-review/', davur_views.page_review, name="page-review"),
    path('page-review/<int:id>', davur_views.filter_review, name="filter-review"),
    path('page-general-customers/', davur_views.page_general_customers, name="page-general-customers"),
    path('page-general-customers/<str:a>', davur_views.filter_customers, name="filter-customers"),
    path('customer-detail/<int:id>', davur_views.customer_detail, name="customer-detail"),
    path('delete-customer/<int:id>', davur_views.delete_customer, name="delete-customer"),
    
    path('online-customers/', davur_views.online_customers, name="online-customers"),


    path('ecom-product-list/', davur_views.ecom_product_list, name="ecom-product-list"),
    path('product-detail/<int:id>', davur_views.product_detail, name="product-detail"),
    path('delete-product/<int:id>', davur_views.delete_product, name="delete-product"),

    # create filter by categories
    path('category/<str:slug>', davur_views.filter_by_categories, name="filter-by-categories"),

    path('ecom-product-order/', davur_views.ecom_product_order, name="ecom-product-order"),

    path('order-status/', davur_views.order_status, name="order-status"),
    path('update-status/<int:id>/<str:status>', davur_views.update_status, name="update-status"),
    
    path('detail-order/<int:id>', davur_views.detail_order, name="detail-order"),

    path('delete-order/<int:id>', davur_views.delete_order, name="delete-order"),

    
    
    

    # demo
    path('demo/', davur_views.revenue, name="revenue"),


]

davur/models.py
from django.db import models

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from users.models import CustomUser


# For Store Owner

#Tabel
class Table(models.Model):
    name_table = models.CharField(max_length=50, blank=False, null=False)
    available = models.BooleanField(default=True)

    def __str__(self):
        return str(self.name_table)

#Customer
class Customer(models.Model):
    name = models.CharField(max_length=100,null=True)
    buy_qty = models.IntegerField(default=1)
    join_date = models.DateTimeField(auto_now_add=True)
    total_spent = models.FloatField(default=0)
    last_order_date = models.DateTimeField(null=True)

    def __str__(self):
        return self.name

#Category
class Category(models.Model):
    name = models.CharField(max_length=100, blank=False, null=True)
    slug = models.SlugField(max_length=100, blank=False, null=True, default=None)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

# Product
class Product(models.Model):
    product_name = models.CharField(max_length=255, blank=False, null=False)
    product_price = models.FloatField(blank=False, null=False)
    description = models.TextField(blank=True, null=False)
    product_qty = models.IntegerField()
    product_code = models.CharField(max_length=20, blank=False, null=True)
    product_image = models.ImageField(upload_to="product_images", blank=False, null=False)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    buy_qty = models.IntegerField(default=0)

    def revenue(self):
        return self.product_price * self.buy_qty

    @property
    def ImageURL(self):
        try:
            url = self.product_image.url
        except:
            url=""
        return url

    def __str__(self):
        return self.product_name
    
    @property
    def rating(self):
        reviews = self.review.all()
        count = len(reviews)
        if count == 0:
            return 0
        else:
            sum = 0
            for review in reviews:
                sum = sum + int(review.rating)
            return round(sum/count,1)

#Produc Review
class Product_review(models.Model):
    product = models.ForeignKey(Product, related_name='review', on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    review_content = models.TextField(blank=False, null=False)
    time = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=False, null=True)

    

    def __str__(self):
        return f"{self.customer}: {self.rating}"

# Restaurant Review    
class Restaurant_review(models.Model):
    # ratingChoices = (
    #     (1, '1'), 
    #     (2, '2'), 
    #     (3, '3'), 
    #     (4, '4'), 
    #     (5, '5')
    # )

    # rating = models.IntegerField(choices=ratingChoices, blank=False, null=False, default=5)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=False)
    review_content = models.TextField(blank=False, null=False)
    time = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def avg(self):
        if (Restaurant_review.objects.all()):
            count = Restaurant_review.objects.count()
            sum = 0
            all_reviews = Restaurant_review.objects.all()
            for review in all_reviews:
                sum = sum + int(review.rating)
            return round(sum/count,1)


    def __str__(self):
        return f"{self.customer}: {self.rating}"
    
 

 # Cart Model

# Cart   
class Cart(models.Model):
    table = models.OneToOneField(Table, on_delete=models.CASCADE, null=True, blank=False)     

    def __str__(self):
        return str(self.id)
    
    @property
    def get_cart_items(self):
        cartitems = self.cartitem_set.all()
        total = sum([item.quantity for item in cartitems])
        return total
    
    @property
    def get_cart_total(self):
        cartitems = self.cartitem_set.all()
        total = sum([item.get_total for item in cartitems])
        return total

# Cart item model
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    
    @property
    def get_total(self):
        total = self.product.product_price * self.quantity
        return total

class NullItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0)



# Date of order
class FilterDate(models.Model):
    filter_date = models.DateField(default=None)

   




# Order
class Order(models.Model):
    customer_name = models.CharField(max_length=100, blank=True, null= True)
    order_id = models.CharField(max_length=20, blank=False, null=True)    
    payment_method = models.CharField(max_length=20, blank=False, null=False)   
    discount = models.CharField(max_length=20, blank=False, null=False)
    total_item = models.IntegerField(default=0)
    total_price = models.FloatField(default=0)
    is_return = models.BooleanField(default=False)
    is_complete = models.BooleanField(default=False)
    filter_date = models.ForeignKey(FilterDate, related_name='filterdate', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def isreturn(self):       
        self.total_price = self.total_price * 0.9
        return round(self.total_price, 2)

    def discount10(self):
        self.total_price = self.total_price * 0.9
        return round(self.total_price, 2)

    def discount20(self):
        self.total_price = self.total_price * 0.8
        return round(self.total_price, 2)
    
    def __str__(self):
        return self.order_id
    
class ListOrder(models.Model):
    product_name = models.CharField(max_length=100,null=True)
    product_price = models.FloatField(default=0)
    product_qty = models.IntegerField(default=0)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=False, null=True)





# For Online Customer




# Cutomer history 
class CustomerHistory(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=False, null=True)
    buy_qty = models.IntegerField(default=0)
    join_date = models.DateTimeField(auto_now_add=True)
    total_spent = models.FloatField(default=0)
    last_order_date = models.DateTimeField(null=True)

    # def __str__(self):
    #     return self.customer
    
# Shipping address
class ShippingAddress(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=False, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    zip = models.IntegerField(null=True)
    mobile = models.IntegerField(null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

# Discount code
class Discount(models.Model):
    code = models.CharField(max_length=20, null=True)
    value = models.IntegerField()

    def __str__(self):
        return self.code

# Customer Cart   
class CartOnline(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=False, null=True)
    discount = models.FloatField(default=0)
    

    def __str__(self):
        return str(self.id)
    
    @property
    def get_cart_items(self):
        cartitems = self.cart.all()
        total = sum([item.quantity for item in cartitems])
        return total
    
    @property
    def get_cart_total(self):
        cartitems = self.cart.all()
        total = sum([item.get_total for item in cartitems])
        total = total - total * self.discount / 100
        return total
    @property
    def get_discount_price(self):
        cartitems = self.cart.all()
        total = sum([item.get_total for item in cartitems])
        total = total * self.discount / 100
        return total
    
    
    
    


# Customer Cart item
class CartItemOnline(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    cart = models.ForeignKey(CartOnline, related_name='cart', on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    
    @property
    def get_total(self):
        total = self.product.product_price * self.quantity
        return total
    
# Null Item
class NullItemOnline(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    cart = models.ForeignKey(CartOnline, related_name='nullitem', on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0)


# Order
class OrderOnline(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=False, null=True)
    order_id = models.CharField(max_length=20, blank=False, null=True)    
    payment_method = models.CharField(max_length=20, blank=False, null=False)   
    discount = models.CharField(max_length=20, blank=False, null=False)
    total_item = models.IntegerField(default=0)
    total_price = models.FloatField(default=0)
    is_return = models.BooleanField(default=False)
    statusChoices = (
        ('Order Placed', 'Order Placed'), 
        ('Packed', 'Packed'),
        ('In Transit', 'In Transit'), 
        ('Delivered', 'Delivered'), 
        ('Completed', 'Completed')
        
    )

    order_status = models.CharField(max_length=50, choices=statusChoices, null=True, default='Order Placed')
    is_paid = models.BooleanField(default=False)

templates/davur/shop/detail-order.html
{% extends 'davur/elements/layouts/admin.html' %}
{% load static %}


{% block additional_css %}
{% endblock %}


{% block content %}

        <div class="row">

        
            
            <h2><a href="{% url 'davur:ecom-product-order' %}">Back</a></h2>
            <br>
        </div>

        <div class="row page-titles">
            <h3 class="text-primary">Order {{order.order_id}}</h3>
            
        </div>
        
                
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div>
                            <h3>Customer: {{order.customer_name}}</h3>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in list_items %}
                                <tr>
                                    <td>{{ i.product_name }}</td>
                                    <td>${{ i.product_price }}</td>
                                    <td>{{ i.product_qty }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div>
                            <div>
                                <label>Payment Method : </label>
                                {{order.payment_method}}
                            </div>
                            {% if order.is_return == True %}
                            <div>
                                <label>Customer Status : Return</label>
                                
                            </div>
                        
                            {% else %}
                            <div>
                                <label>Customer Status : New</label>
                               
                            </div>
                            {% endif %}
                            <div>
                            {% if order.is_return == True %}
                                <label>Discount: 10% for return customer</label>
                            {% endif %}
                            </div>
                            <div>
                                <label>Discount : </label>
                                {{order.discount}}%
                            </div>
                            <div>
                                <label>Buy Date : </label>
                                {{order.created_at}}
                            </div>
                            <div>
                                <label>Total Items : </label>
                                {{order.total_item}}
                            </div><hr>
                            <div>
                                
                                <strong>Total Price: {{order.total_price}}</strong>
                            </div><hr>
                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <div style="margin: 5px 0 50px 0" class="container">
                <button type="button" class="btn btn-danger col-2 mx-auto " data-bs-toggle="modal" data-bs-target="#myModal{{order.id}}">Delete</button>       
            </div>
            <!-- The Modal -->
            <div class="modal" id="myModal{{order.id}}">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Are you sure ?</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            <a href="{% url 'davur:delete-order' order.id %}" class="btn btn-primary">Delete</a>            
                        </div>
                    </div>
                </div>
            </div>

            


{% endblock %}



{% block additional_js %}
{% endblock %}

templates/davur/shop/product-detail.html
{% extends 'davur/elements/layouts/admin.html' %}
{% load static %}


{% block additional_css %}
{% endblock %}


{% block content %}
<div class="row">

        
            
            <h2><a href="{% url 'davur:ecom-product-list' %}">Back</a></h2>
            <br>
        </div>

        <div class="row page-titles">
            <h3 class="text-primary">Product Id : {{product.product_code}}</h3>
            
        </div>
        
                
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div>
                            <h3>{{product.product_name}}</h3>
                            
                        </div>
                        <div>
                            <div>
                                <label>Price : </label>
                                {{product.product_price}}
                            </div>
                            <div>
                                <label>Quantity : </label>
                                {{product.product_qty }}
                            </div>
                            <div>
                                <label>Category : </label>
                                {{product.category}}
                            </div>
                            <div>
                                <label>Buy quantity : </label>
                                {{product.buy_qty}}
                            </div>
                            <div>
                                <label>Product code : </label>
                                {{product.product_code}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <div style="margin: 5px 0 50px 0" class="container">
                <button type="button" class="btn btn-danger col-2 mx-auto " data-bs-toggle="modal" data-bs-target="#myModal{{product.id}}">Delete</button>       
            </div>
            <!-- The Modal -->
            <div class="modal" id="myModal{{product.id}}">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Are you sure ?</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>
                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            <a href="{% url 'davur:delete-product' product.id %}" class="btn btn-primary">Delete</a>            
                        </div>
                    </div>
                </div>
            </div>

            

{% endblock %}



{% block additional_js %}
{% endblock %}

templates/davur/shop/product-list-by-categories.html
{% extends 'davur/elements/layouts/admin.html' %}
{% load static %}


{% block additional_css %}
{% endblock %}


{% block content %}
       <div class="row page-titles">
            <ol class="breadcrumb">
                    <button type="button" class="btn">
                        <a href="{% url 'davur:ecom-product-list' %}">
                            <strong>All</strong>
                        </a>
                    </button>
                {% for category in categories%}
                    {% comment %} <li class="breadcrumb-item active"><a href="javascript:void(0)">{{ category.name }}</a></li> {% endcomment %}
                    <button type="button" class="btn">
                        <a href="{% url 'davur:filter-by-categories' category.slug %}">
                            <strong class="{% if active_categoty.slug == category.slug %} text-primary {% endif %}">{{ category.name }}</strong>
                        </a>
                    </button>
                {% endfor %}
            </ol>
        </div>
        <div class="row">
            {% for product in products %}
                <div class="col-lg-12 col-xl-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="row m-b-30">
                                <div class="col-md-5 col-xxl-12">
                                    <div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
                                        <div class="new-arrivals-img-contnent">
                                            <img class="img-fluid" src="{{ product.ImageURL }}" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-7 col-xxl-12">
                                    <div class="new-arrival-content position-relative">
                                        <h4>{{ product.product_name }}</h4>
                                        {% if product.product_qty > 0 %}
                                        <p>Quantity: {{product.product_qty}}<p>
                                        
                                        {% else %}
                                        <p class = "text-danger">Out of stock</p>
                                        {% endif %}
                                        
                                        <h4><strong class="text-danger">${{ product.product_price }}</strong></h4><br>
                                        <a style="outline:none" class="btn btn-primary" href="{% url 'davur:product-detail' product.id %}">View product</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
                <div style= "margin-left:50px; margin-top:10px" class="pagination">
                    <span class="step-links">
                    
                        {% if products.has_previous %}
                            <a href="?page=1">&laquo; First</a>
                            <a href="?page={{ products.previous_page_number }}">Previous</a>
                        {% endif %}

                        <span style="margin: 0 10px" class="current">
                            Page {{ products.number }} of {{ products.paginator.num_pages }}
                        </span>

                        {% if products.has_next %}
                            
                            <a href="?page={{ products.next_page_number }}">Next</a>
                            <a href="?page={{ products.paginator.num_pages }}" >Last &raquo;</a>
                            
                        {% endif %}
                   
                    </span>
                </div>
            <!-- review -->
            {% comment %} <div class="modal fade" id="reviewModal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Review</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal">
                            </button>
                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="text-center mb-4">
                                    <img class="img-fluid rounded" width="78" src="{% static 'davur/images/avatar/1.jpg' %}" alt="DexignZone">
                                </div>
                                <div class="mb-3">
                                    <div class="rating-widget mb-4 text-center">
                                        <!-- Rating Stars Box -->
                                        <div class="rating-stars">
                                            <ul id="stars">
                                                <li class="star" title="Poor" data-value="1">
                                                    <i class="fa fa-star fa-fw"></i>
                                                </li>
                                                <li class="star" title="Fair" data-value="2">
                                                    <i class="fa fa-star fa-fw"></i>
                                                </li>
                                                <li class="star" title="Good" data-value="3">
                                                    <i class="fa fa-star fa-fw"></i>
                                                </li>
                                                <li class="star" title="Excellent" data-value="4">
                                                    <i class="fa fa-star fa-fw"></i>
                                                </li>
                                                <li class="star" title="WOW!!!" data-value="5">
                                                    <i class="fa fa-star fa-fw"></i>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <textarea class="form-control" placeholder="Comment" rows="5"></textarea>
                                </div>
                                <button class="btn btn-success btn-block">RATE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div> {% endcomment %}
        </div>

{% endblock %}



{% block additional_js %}
{% endblock %}