dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('',include('davur.urls', namespace='davur')),
    # path('frontend/',include('frontend.urls', namespace='frontend')),

    path('davur/',include('davur.urls', namespace='davur')),
    path('',include('frontend.urls', namespace='frontend')),

    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),
    
]
if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header  =  "Davur Dashboard"  
admin.site.site_title  =  "Dashboard"
admin.site.index_title  =  "Dashboard"

davur/urls.py
from django.urls import path
from davur import davur_views
from users import users_views

app_name = 'davur'
urlpatterns = [

    path('users/', users_views.users, name="users"),
    path('user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('add-user/', users_views.add_user, name="add-user"),
    path('edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),

    path('login/', users_views.login_user, name="login"),
    path('logout/', users_views.logout_user, name="logout"),

    path('group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('group-add/', users_views.group_add, name="group-add"),

    path('edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('signup/', users_views.signup, name="signup"),
    path('activate/<uidb64>/<token>/', users_views.activate, name='activate'),

    path('', davur_views.index, name="index"),
    path('dashboard/', davur_views.dashboard, name="dashboard"),
    path('page-analytics/', davur_views.page_analytics, name="page-analytics"),
    path('page-review/', davur_views.page_review, name="page-review"),
    path('page-review/<int:id>', davur_views.filter_review, name="filter-review"),
    path('page-general-customers/', davur_views.page_general_customers, name="page-general-customers"),
    path('page-general-customers/<str:a>', davur_views.filter_customers, name="filter-customers"),
    path('customer-detail/<int:id>', davur_views.customer_detail, name="customer-detail"),
    path('delete-customer/<int:id>', davur_views.delete_customer, name="delete-customer"),
    
    path('online-customers/', davur_views.online_customers, name="online-customers"),


    path('ecom-product-list/', davur_views.ecom_product_list, name="ecom-product-list"),
    path('product-detail/<int:id>', davur_views.product_detail, name="product-detail"),
    path('delete-product/<int:id>', davur_views.delete_product, name="delete-product"),

    # create filter by categories
    path('category/<str:slug>', davur_views.filter_by_categories, name="filter-by-categories"),

    path('ecom-product-order/', davur_views.ecom_product_order, name="ecom-product-order"),

    path('order-status/', davur_views.order_status, name="order-status"),
    path('update-status/<int:id>/<str:status>', davur_views.update_status, name="update-status"),
    
    path('detail-order/<int:id>', davur_views.detail_order, name="detail-order"),

    path('delete-order/<int:id>', davur_views.delete_order, name="delete-order"),

    
    
    

    # demo
    path('demo/', davur_views.revenue, name="revenue"),


]

frontend/urls.py
from django.urls import path
from frontend import frontend_views

app_name = 'frontend'
urlpatterns = [

    # For customer
    path('', frontend_views.home_page, name="home-page"),
    path('sign-up/', frontend_views.register_page, name="register"),
    path('login/', frontend_views.login_page, name="login-page"),
    path('logout/', frontend_views.logout_page, name="logout-page"),

    path('product/<int:id>', frontend_views.product_detail, name="view-product"),
    path('cart/', frontend_views.cart_page, name="cart-page"),
    path('addtocart-onl/', frontend_views.addtocart_online, name="addtocart-online"),
    path('updatecart-onl/', frontend_views.updateCart_online, name ='updatecart-online'),
    path('delete-cart-item-onl/', frontend_views.deleteCartItem_online, name ='delete-cart-item-online'),
    path('delete-null-item-onl/', frontend_views.deleteNullItem_online, name ='delete-null-item-online'),
    path('discount-code/', frontend_views.discount_code, name ='discount-code'),
    
    path('checkout/', frontend_views.checkout_page, name="checkout-page"),
    path('purchase/', frontend_views.purchase_page, name="purchase-page"),
    path('thank-you/<str:id>', frontend_views.thankyou_page, name="thank-you"),

    path('customer_review/<int:id>', frontend_views.customer_review, name ='customer-review'),

    path('order-history/', frontend_views.order_history, name ='order-history'),
    path('tracking-order/', frontend_views.tracking_order, name ='tracking-order'),



    #For store owner

    path('front-authentication/', frontend_views.front_authentication, name="front-authentication"),
    # path('front-people/', frontend_views.front_people, name="front-people"),
    path('front-upload-item/', frontend_views.front_upload_item, name="front-upload-item"),
    # path('front-login/', frontend_views.front_login, name="front-login"),
    path('page-register/', frontend_views.page_register, name="page-register"),
    # path('update_item/', frontend_views.updateItem, name='update-item'),
    path('search/', frontend_views.search, name="search"),
    path('category/<str:slug>/<int:id>', frontend_views.category, name="category"),
    path('table/', frontend_views.table, name = 'table'),
    path('cart/<int:id>', frontend_views.cart, name = 'cart'),
    path('cart-demo/<int:id>', frontend_views.cart_demo, name = 'cart-demo'),
    path('checkout/<int:id>', frontend_views.checkout, name = 'checkout'),
    path('purchase/<pk>', frontend_views.purchase, name = 'purchase'),
    path('success/<int:id>', frontend_views.success, name = 'success'),
    path('addtocart/',frontend_views.addtocart, name='addtocart'),
    path('updatecart/', frontend_views.updateCart, name ='updatecart'),
    path('delete-cart-item/', frontend_views.deleteCartItem, name ='delete-cart-item'),
    path('delete-null-item/', frontend_views.deleteNullItem, name ='delete-null-item'),
    path('chartjs/', frontend_views.chartJs, name ='chart'),
    path('review/<int:id>', frontend_views.review, name ='review'),
    path('thankyou/', frontend_views.thankyou, name ='thankyou'),

    
    

]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render

# Create your views here.

templates/frontend/cart-demo.html
{% extends 'frontend/elements/layouts/base.html' %}
{% load static %}
{% block additional_css %}
{% endblock %}
{% block cart %}
<div class="row parent">    
	<div class=" col-lg-12 cart-page">
		<div class="box-element">			
			<table class="table">	
				<tr>
					<th><h5>Items: <strong>{{cart.get_cart_items}}</strong></h5></th>
					<th><h5>Total:<strong>{{cart.get_cart_total}}</strong></h5></th>
				</tr>
			</table>
		</div>
		<br>
		<div class="box-element">
			<div class="cart-row">
				<div style="flex:2"></div>
				<div style="flex:2"><strong>Item</strong></div>
				<div style="flex:1"><strong>Price</strong></div>
				<div style="flex:1"><strong>Quantity</strong></div>
				<div style="flex:1"><strong>Total</strong></div>
                <div style="flex:1"><strong></strong></div>
			</div>
            <div>
                {% if items %}           
                    {% for item in items %}                    
                    <div class="cart-row product-data2">
                        <div style="flex:2"><img class="row-image" src="{{item.product.ImageURL}}"></div>
                        <div style="flex:2"><p>{{item.product.product_name}}</p></div>                    
                        {% csrf_token %}
                        <input type="hidden" value="{{ cart.id }}" class="cart_id">
                        <input type="hidden" value="{{ item.product.id }}" class="prod_id">
                        <div style="flex:1"><p>{{item.product.product_price}}</p></div>
                        <div style="flex:1">
                            <div class="input-group text-center mb-3" style="width:130px;">
                                <button class = "input-group-text changeQuantity decrement-btn">-</button>
                                <input type ='text' name="quantity" class ="form-control qty-input text-center" value="{{item.quantity}}">
                                <button class = "input-group-text changeQuantity increment-btn">+</button>
                            </div>                        
                        </div>
                        <div style="flex:1"><p></p>{{item.get_total}}</div>
                        
                        <div style="flex:1">
                            <button class="btn btn-danger delete-cart-item remove" onClick="window.location.reload()"><i class = "fa fa-trash"></i>Remove</button>
                        </div>
                    </div>
                    {% endfor %}                
                <div>
                    <button style="text-align:center">
                        <a style = 'text-decoration: none; color:black;' href="{% url 'frontend:checkout' cart.id %}">Check Out</a>
                    </button>
                </div>
                <hr>    
                {% else %}
                <div style="flex:1"><h6>Your Cart Is Empty</h6></div>
                <hr>
                {% endif %}
            </div>
            <div class="null-data">
                {% if nullitems %}
                {% for nullitem in nullitems %}                    
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{{nullitem.product.ImageURL}}"></div>
                        <div style="flex:2"><p>{{nullitem.product.product_name}}</p></div>                            
                        {% if nullitem.quantity > 1 %}
                        <div style="flex:1"><h6>Only {{ nullitem.quantity }} products available</h6></div>
                        {% elif nullitem.quantity == 1 %}
                        <div style="flex:1"><h6>Only {{ nullitem.quantity }} product available</h6></div>
                        {% else %}
                        <div style="flex:1"><h6>Out of stock</h6></div>
                        {% endif %}                           
                        <div style="flex:1"></div>                            
                    </div>
                {% endfor %}
                {% csrf_token %}
                <input type="hidden" value="{{ cart.id }}" class="cart_id">
                <div style="flex:1">
                    <button class="btn btn-danger delete-null-item remove" onClick="window.location.reload()"><i class = "fa fa-trash"></i>Remove</button>
                </div>
                {% endif %}
            </div>
		</div>
        
	</div>

	<div class='row'>	
        {% for product in products %}
            <div class='col-xl-6 col-xxl-3 col-lg-3 col-md-6 col-sm-3 product-data'>
                <div class="card item-card">    
                    
                    <div class='box-element product'>
                        <div class="card-body p-0">
                            <img class="img-fluid" src="{{ product.ImageURL}}">
                            <div class="info">
                                <h6><strong>{{ product.product_name }}</strong></h6>
                                <hr>
                                {% csrf_token %}
                                <input type="hidden" value="{{ cart.id }}" class="cart_id">
                                <input type="hidden" value="{{ product.id }}" class="prod_id">
                                <label for="Quantity">Quantity: </label>
                                {% if product.product_qty > 0 %}
                                <label>{{ product.product_qty }}</label><br>
                                <label style="color:green">Instock</label>
                                {% else %}
                                <label>0</label><br>
                                <label style="color:red">Out of stock</label>                   
                                {% endif %} 
                                <h4 class="display: inline-block; float:right ">${{ product.product_price | floatformat:2 }}</h4>
                            </div>                      
                                <div class="input-group text-center mb-3" style="width:130px;">
                                    <button class = "input-group-text decrement-btn">-</button>
                                    <input type ='text' name="quantity" class ="form-control qty-input text-center" value='1'>
                                    <button class = "input-group-text increment-btn">+</button>
                                </div>
                                <button type='button' class='btn btn-primary me-3 add-btn addToCartBn reload' onClick="window.location.reload()">Add To Cart</button>
                                
                        </div>    
                    </div>
                </div>
            </div>
        {% endfor %}
        

    </div>
</div>

{% endblock cart %}

templates/frontend/checkout.html
{% extends 'frontend/elements/layouts/base.html' %}
{% load static %}
{% block additional_css %}
{% endblock %}
{% block checkout %}
<head>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
  margin-top:150px;
  
  
}
</style>
</head>
{% include 'davur/elements/nav-header.html' %}
{% include 'davur/elements/header.html' %}
<body>



<div class="container">
<h3>Check Out</h3>
  <form method ='post' action="">
  {% comment %} <form method ='post' action=""> {% endcomment %}
  {% csrf_token %}
    <label>Customer Name</label>
    <input type='text' name="customer_name">
   <label>Payment Method</label>    
   <select name='payment_method' >
      <option value="Cash" >Cash</option>
      <option value="Card" >Card</option>
    </select>
    <label>Discount</label>   
    <select name='discount' >
      <option value="0" >0%</option>
      <option value="10" >10%</option>
      <option value="20" >20%</option>
    </select>
    <input type="submit" value="Submit">
  </form>
</div>
</body>


{% endblock checkout %}

templates/frontend/order-category.html
{% extends 'frontend/elements/layouts/base.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}
{% include 'davur/elements/nav-header.html' %}
{% include 'davur/elements/header.html' %}
<div class="content-wrapper">
    <!-- row -->
    <div class="listcontent-area">
        <aside class="cart-area  dz-scroll cart-page" id="cart_area">
            <div class="" >
                <div class="h-100">
                    <div class="card rounded-0">
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table text-black">
                                    <thead>
                                        <tr>
                                            <th>ITEM</th>
                                            <th>QNT.</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody style="overflow: auto; width: 150px">

                                    
                                    {% if nullitems %}
                                    {% for nullitem in nullitems %} 
                                        <tr>                   
                                            <td><span class="font-w500">{{nullitem.product.product_name}}</span></td>
                                            {% if nullitem.quantity > 1 %}
                                            <td style="flex:1"><h6>Only {{ nullitem.quantity }} products available</h6></td>
                                           <td></td>
                                            {% elif nullitem.quantity == 1 %}
                                            <td style="flex:1"><h6>Only {{ nullitem.quantity }} product available</h6></td>
                                            <td></td>
                                            {% else %}
                                            <td style="flex:1"><h6>Out of stock</h6></td>
                                            <td></td>
                                            {% endif %} 
                                        </tr>   
                                    {% endfor %}
                                    {% csrf_token %}
                                    
                                    <tr class="null-data">
                                        <input type="hidden" value="{{ cart.id }}" class="cart_id">
                                            <td>
                                                <div>
                                                    <button class="btn btn-danger delete-null-item remove" onClick="window.location.reload()">Remove</button>
                                                </div>
                                            </td>
                                            <td></td>
                                            <td></td>
                                    </tr>
                                    {% endif %}
                                    



                                    {% if items %}                                                                   
                                    {% for item in items %}
                                        <tr class="product-data2">
                                            <td><span class="font-w500">{{item.product.product_name}}</span></td>
                                            {% csrf_token %}
                                            <input type="hidden" value="{{ cart.id }}" class="cart_id">
                                            <input type="hidden" value="{{ item.product.id }}" class="prod_id">
                                            
                                            <td>
                                                <div class="input-group text-center d-flex justify-content-end " style="width:145px; margin-right:0px">
                                                    <button class = "input-group-text w-25 decrement-btn">-</button>
                                                    <input style="height:45px" type ='text' name="quantity" class ="form-control qty-input text-center" value="{{item.quantity}}">
                                                    <button  class = "input-group-text w-25 increment-btn">+</button>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="d-flex justify-content-end">
                                                    <button style="margin-right:5px" class="btn btn-primary changeQuantity" onClick="window.location.reload()">Update</button>
                                                    <button style="color:white" class="btn btn-danger delete-cart-item remove" onClick="window.location.reload()">X</button>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    {% else %}
                                    <tr>
                                        <td><h6>Your Cart Is Empty</h6></td>
                                    </tr>
                                    {% endif %}
                                    
                                    
                                      
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="card-order-footer">
                        <div class="btn_box">
                            <div class="row no-gutter mx-0">
                                <a href="" id="home-counter-tab" class="btn btn-light btn-block col-6 m-0 rounded-0">Confirm</a>
                                <a href="{% url 'frontend:table'  %}" id="home-counter-tab" class="btn btn-danger btn-block col-6 m-0 rounded-0">Back</a>
                                <a href="{% url 'frontend:checkout' cart.id %}" id="place-order-tab" class="btn btn-primary btn-block col-6 m-0 rounded-0">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </aside>
        <!--Place-An-Order-->    
        <div class="row">
                <!-- Search -->
                <div style="margin:30px 500px 10px 20px; width: 300px" class="search-area style-1 mb-4">
                    <form method = 'post' action = '{% url "frontend:search" %}'>
                    
                    {% csrf_token %}
                    <input type="hidden" value="{{cart.id}}" name="id_cart"> 
                    <input type="text" class="form-control" placeholder="Search here..." name="searched">
                    <div style= "margin-top:10px" class="input-group-append">
                        <button class=" btn btn-primary btn-rounded">Search<i class="flaticon-381-search-2 scale3 ms-3"></i></button>
                    </div>
                    </form>
                </div>
                <div class="row">
                    <div class="row page-titles">
                    <!-- Category -->
                        <ol class="breadcrumb">
                                <button type="button" class="btn" name ='category'>
                                    <a href="{% url 'frontend:cart' table_id %}">
                                        <strong>All</strong>
                                    </a>
                                </button>
                            {% for category in categories%}
                                
                                <button type="button" class="btn" name ='category'>
                                    <a href="{% url 'frontend:category' category.slug cart.id %}">
                                        <strong class="{% if active_category.slug == category.slug %} text-primary {% endif%}">{{ category.name }}</strong>
                                    </a>
                                </button>
                            {% endfor %}
                        
                        </ol>
                    </div>
                    <!-- Search Results -->
                    {% comment %} <div style="visibility: {{no_search}}">
                        <div style="visibility: {{found}}" >
                            <h5>Result searched for: {{searched }}</h5><br>
                        </div>
                        <div style="visibility: {{not_found}}">
                            <h5 >Result searched for: {{searched }} </h5>
                            <h5>Not Found</h5>
                            <br>
                        </div>
                    </div> {% endcomment %}
                    <!-- Products List -->
                    {% for product in products %}   
                    <div class="col-xl-3 col-xxl-4 col-lg-6 col-md-12 col-sm-6 product-data">
                        <div class="card item-card ">
                            <div class="card-body p-0">
                                <img src="{{ product.ImageURL }}" class="img-fluid" alt="">
                                <div class="info">
                                    <h4 class="name">{{ product.product_name}}</h4>
                                    <hr>
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ cart.id }}" class="cart_id">
                                    <input type="hidden" value="{{ product.id }}" class="prod_id">
                                    <label for="Quantity">Quantity: </label>
                                    {% if product.product_qty > 0 %}
                                    <label>{{ product.product_qty }}</label><br>
                                    <label style="color:green">Instock</label>
                                    {% else %}
                                    <label>0</label><br>
                                    <label style="color:red">Out of stock</label>                   
                                    {% endif %} 
                                    <h4 style="margin-top:10px" class="display: inline-block; float:right ">${{ product.product_price | floatformat:2 }}</h4>
                                </div>
                                
                                <div style="margin-bottom:10px; padding-left:35px">                                                     
                                    <div class="input-group text-center mb-3" style="width:150px;">
                                        <button class = "input-group-text decrement-btn">-</button>
                                        <input type ='text' name="quantity" class ="form-control qty-input text-center" value='1'>
                                        <button class = "input-group-text increment-btn">+</button>
                                    </div>
                                    <button style="margin-left:20px" type='button' class='btn btn-primary me-3 add-btn addToCartBn reload text-center' onClick="window.location.reload()">Add To Cart</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% comment %} {% block additional_js %}
<script>

    
    
		  
	function ItemsCarousel()
	{
	
		/*  testimonial one function by = owl.carousel.js */
		jQuery('.item-carousel').owlCarousel({
			loop:true,
			margin:10,
			nav:true,
			center:true,
			autoWidth:true,
			autoplay:true,
			dots: false,
			items:4,
			navText: ['', ''],
			breackpoint:[
			
			
			]
			
		})
	}
	
	jQuery(window).on('load',function(){
		setTimeout(function(){
			ItemsCarousel();
		}, 1000); 
	});
	
	function handleTabs(){
		$('#add-order-content,#place-order').css("display","none");	
		$('#add-order').on('click',function(){
			$('#add-order-content').css("display","block");	
			$('#home-counter').css("display","none");	
		})
		$('#place-order-tab').on('click',function(){
			$('#place-order').css("display","block");	
			$('#add-order-content').css("display","none");	
		})
		$('#place-order-cancel').on('click',function(){
			$('#place-order').css("display","none");	
			$('#add-order-content').css("display","block");	
		})
		$('#home-counter-tab').on('click',function(){
			$('#home-counter').css("display","block");	
			$('#add-order-content').css("display","none");	
		})
	}
	handleTabs();

	</script>
{% endblock %} {% endcomment %}

templates/frontend/thankyou.html
{% extends 'frontend/elements/layouts/base.html' %}
{% load static %}
{% block additional_css %}
{% endblock %}
{% block success %}
<head>
{% include 'davur/elements/nav-header.html' %}
{% include 'davur/elements/header.html' %}
</head>
   



<div style="margin-top:150px" class="jumbotron text-center">
  <h1 class="display-3">Thank You</h1>
  <p class="lead">Thank for your support, hope you have a nice day. Best regard! </p>
  <hr>
  
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="{% url 'frontend:table' %}" role="button">Back To Place Order</a>
  </p>
  
</div>

{% endblock success %}